Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles import views as static_views
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^authentication/', include('authentication.urls')),
    url(r'^navbar/', include('navbar.urls')),
    url(r'^link/', include('link.urls')),
    url(r'^mood/', include('mood.urls')),
    url(r'^', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.STATIC_ROOT},
            name='static'),
        url(r'^media/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.MEDIA_ROOT},
            name='media'),

    ]

DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import url

from views import get_ueditor_controller

urlpatterns = [
    url(r'^controller/$',get_ueditor_controller)
]

mood/urls.py
from django.conf.urls import url
from mood import views

urlpatterns = [
    url(r'^add/$', views.MoodCreateView.as_view(), name='mood-add'),
    url(r'^list/$', views.MoodListView.as_view(), name='mood-list'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.MoodUpdateView.as_view(), name='mood-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.MoodDeleteView.as_view(), name='mood-delete'),
    url(r'^timeline/$', views.MoodTimeLineView.as_view(), name='mood-time-line')
]

mood/models.py
from __future__ import unicode_literals

from django.db import models
from Blog.local_settings import storage

MOOD_TYPE_CHOICE = (
    ('T', 'Text'),
    ('I', 'Image'),
    ('B', 'block_quote')
)


class Mood(models.Model):
    title = models.CharField(max_length=128, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    mood_type = models.CharField(max_length=1, choices=MOOD_TYPE_CHOICE, default='T')
    image = models.ImageField(upload_to='./image/mood/%Y/%m/%d/', null=True, blank=True)
    create_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.content

    def get_small_image_url(self):
        if storage == 'qiniu':
            return self.image.url + '?imageView2/2/w/350'
        else:
            return self.image.url

    class Meta:
        ordering = ['-create_time']

mood/views.py
from django.core.urlresolvers import reverse_lazy
from utils.mixin import AjaxableResponseMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from mood.models import Mood
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from website.mixin import FrontMixin


class MoodCreateView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    login_url = reverse_lazy('user-login')
    model = Mood
    fields = ['title', 'content', 'mood_type', 'image']
    success_url = reverse_lazy('mood-list')

    def get_context_data(self, **kwargs):
        context = super(MoodCreateView, self).get_context_data(**kwargs)
        context['active_page'] = 'mood-add'
        return context

    def get_template_names(self):
        if self.request.META['HTTP_USER_AGENT'].lower().find('mobile') > 0:
            return 'mood/mood_create_form_mobile.html'
        else:
            return 'mood/mood_create_form.html'


class MoodListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user-login')
    model = Mood
    context_object_name = 'mood_list'

    def get_context_data(self, *args, **kwargs):
        context = super(MoodListView, self).get_context_data(**kwargs)
        context['active_page'] = 'mood-list'
        return context


class MoodUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    login_url = reverse_lazy('user-login')
    model = Mood
    context_object_name = 'mood'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('mood-list')
    fields = ['title', 'content', 'mood_type', 'image']

    def get_context_data(self, *args, **kwargs):
        context = super(MoodUpdateView, self).get_context_data(**kwargs)
        context['active_page'] = 'mood-update'
        return context


class MoodDeleteView(LoginRequiredMixin, AjaxableResponseMixin, DeleteView):
    login_url = reverse_lazy('user-login')
    model = Mood
    success_url = reverse_lazy('link-list')

    def post(self, request, *args, **kwargs):
        super(MoodDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})


class MoodTimeLineView(FrontMixin, ListView):
    model = Mood
    paginate_by = 20
    template_name = 'mood/mood_time_line.html'
    context_object_name = 'mood_list'

templates/mood/mood_create_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    添加碎碎念
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="mood_type" class="col-sm-1 control-label">类型：</label>
                <div class="col-sm-9">
                    <select name="mood_type" id="mood_type" class="form-control">
                        <option value="T">文字</option>
                        <option value="I">图文</option>
                        <option value="B">引用</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <textarea name="content" id="content" rows="5" wrap="hard" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="img" class="col-sm-1 control-label">配图：</label>
                <div class="col-sm-3">
                    <input type="file" id="image" name="image" class="form-control">
                </div>
            </div>
            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "mood-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>
{% endblock %}

templates/mood/mood_create_form_mobile.html
{% extends 'website/base.html' %}
{% load staticfiles %}

{% block title %}{% endblock %}

{% block external_header %}
    <script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
{% endblock %}

{% block body %}
    {% include 'website/frontend/header.html' %}
    <div class="main-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 left-content">
                    <div class="col-md-12 article">
                        <form class="form-horizontal" id="data-form">
                            <div class="form-group">
                                <label for="title" class="col-sm-1 control-label">标题：</label>
                                <div class="col-sm-9">
                                    <input type="text" id="title" name="title" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="mood_type" class="col-sm-1 control-label">类型：</label>
                                <div class="col-sm-9">
                                    <select name="mood_type" id="mood_type" class="form-control">
                                        <option value="T">文字</option>
                                        <option value="I">图文</option>
                                        <option value="B">引用</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="content" class="col-sm-1 control-label">内容：</label>
                                <div class="col-sm-9">
                                    <textarea name="content" id="content" rows="5" wrap="hard" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="img" class="col-sm-1 control-label">配图：</label>
                                <div class="col-sm-3">
                                    <input type="file" id="image" name="image" class="form-control">
                                </div>
                            </div>
                            <button class="btn btn-info" id="submit-btn">添加</button>
                            <input type="reset" name="reset" style="display: none;">
                        </form>
                    </div>
                </div>
                {% include 'utils/modal.html' %}
            </div>
        </div>
    </div>
    {% include 'website/frontend/footer.html' %}
{% endblock %}

{% block external_js %}
<script type="text/javascript">
    $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "mood-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
</script>
{% endblock %}

templates/mood/mood_list.html
{% extends 'website/backend/backend_base.html' %}
{% load static %}

{% block option-title %}
    碎碎念列表
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <table class="table table-hover table-responsive table-condensed dashboard-table">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>标题</th>
                    <th>类型</th>
                    <th>发布时间</th>
                    <th>内容</th>
                    <th>图片</th>
                    <th>动作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in mood_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.get_mood_type_display }}</td>
                        <td>{{ item.create_time }}</td>
                        <td>{{ item.content }}</td>
                        <td>
                            {% if item.mood_type == 'I' %}
                                <button data-url="{% get_media_prefix%}{{ item.image }}" class="btn btn-info photo-view" role="button" >查看</button>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'mood-update' item.pk %}" class="btn btn-warning" role="button">修改</a>
                            &emsp;
                            <button class="btn btn-danger" role="button" data-id="{{ item.id }}">删除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="photo-modal" role="dialog" aria-labelledby="photo-modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">查看图片</h4>
                </div>
                <div class="modal-body">
                    <img src="" alt="" id="view-photo" width="100%">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('.btn-danger').on('click',
            function (e) {
                e.preventDefault();
                var dom_item = this;
                $.ajax({
                    type:"POST",
                    dataType:'json',
                    data:{},
                    url:'{% url "mood-delete" 00 %}'.replace('0', this.dataset['id']),
                    success:function(data){
                        var state = data.state;
                        if(state == 'success'){
                            dom_item.parentElement.parentElement.setAttribute('hidden','');
                            showModal('success', "删除成功！")
                        }
                    },
                    error:function(data){
                        alert(data);
                    }
                });
            })
    </script>
    <script type="text/javascript">
        $('.photo-view').on('click', function(e) {
            var dom_item = this;
            var photo_item = $('#view-photo');
            photo_item.attr('src', dom_item.dataset['url']);
            $('#photo-modal').modal();
        })
    </script>
{% endblock %}

templates/mood/mood_nav.html
<ul class="nav nav-sidebar">
    <li id="mood-list"><a href="{% url 'mood-list' %}">碎碎念-列表</a></li>
    <li id="mood-add"><a href="{% url 'mood-add' %}">碎碎念-添加</a></li>
    <li id="mood-update"><a href="{% url 'mood-list' %}">碎碎念-更新</a></li>
</ul>

templates/mood/mood_time_line.html
{% extends 'website/frontend/frontend_base.html' %}
{% load static %}


{% block title %}
    碎碎念
{% endblock %}

{% block external_header %}
    <script type="text/javascript" src="{% static 'js/timeline.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/timeline.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
{% endblock %}

{% block left %}
    <div class="col-md-12 timelinebox">
        <div class="timeline animated">
            {% for mood in mood_list %}
                <div class="timeline-row">
                    <div class="timeline-time"><small>{{ mood.create_time|date:"Y-m-d" }}</small>{{ mood.create_time|time:"H:i:s" }}</div>
                    <div class="timeline-icon">
                        {% if mood.mood_type == 'T' %}
                            <div class="bg-primary"><i class="fa fa-pencil"></i></div>
                        {% elif mood.mood_type == 'B' %}
                            <div class="bg-warning"><i class="fa fa-quote-right"></i></div>
                        {% elif mood.mood_type == 'I' %}
                            <div class="bg-info"><i class="fa fa-camera"></i></div>
                        {% endif %}
                    </div>
                    <div class="panel timeline-content">
                        <div class="panel-body">
                            {% if mood.title %}
                                <h2>{{ mood.title }}</h2>
                            {% endif %}
                            {% if mood.mood_type == 'B' %}
                                <blockquote>
                                    <p>{{ mood.content }}</p>
                                </blockquote>
                            {% elif mood.mood_type == 'I' %}
                                <a href="{% get_media_prefix %}{{ mood.image }}" target="_blank">
                                    <img class="img-responsive" src="{{ mood.get_small_image_url }}" />
                                </a>
                                <p>{{ mood.content }}</p>
                            {% else %}
                                <p>{{ mood.content }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/mood/mood_update_form.html
{% extends 'website/backend/backend_base.html' %}
{% load static %}

{% block option-title %}
    更新碎碎念
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" value="{{ mood.title }}">
                </div>
            </div>
            <div class="form-group">
                <label for="mood_type" class="col-sm-1 control-label">类型：</label>
                <div class="col-sm-9">
                    <select name="mood_type" id="mood_type" class="form-control">
                        <option value="T" {% if mood.mood_type == 'T' %} selected{% endif %}>文字</option>
                        <option value="I" {% if mood.mood_type == 'I' %} selected{% endif %}>图文</option>
                        <option value="B" {% if mood.mood_type == 'B' %} selected{% endif %}>引用</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <textarea name="content" id="content" rows="5" wrap="hard" class="form-control">{{ mood.content }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="img" class="col-sm-1 control-label">配图：</label>
                <div class="col-sm-9">
                    <input type="file" id="image" name="image" class="form-control">
                    {% if mood.image %}
                        <span class="help-block" id="helpBlock">当前图片：<a href="{% get_media_prefix%}{{ mood.image }}">{% get_media_prefix%}{{ mood.image }}</a>,不做修改则上空留空。</span>
                    {% endif %}
                </div>
            </div>
            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "mood-update" mood.id  %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>
{% endblock %}

templates/mood/mood_weight.html
{% load static %}
<div class="col-md-12 article">
    <div class="col-md-12 text-center">
        <h2 class="category-header">碎碎念</h2>
        <hr>
    </div>
    <div class="col-md-12">
        {% if mood.mood_type == 'T' %}
            <p>{{ mood.content }}</p>
        {% elif mood.mood_type == 'I' %}
            <a href="{% get_media_prefix %}{{ mood.image }}" target="_blank">
                <img class="img-responsive" src="{{ mood.get_small_image_url }}" />
            </a>
            <p>{{ mood.content }}</p>
        {% else %}
            <blockquote><p>{{ mood.content }}</p></blockquote>
        {% endif %}
    </div>
    <div class="col-md-12">
        <p class="text-right"><small>{{ mood.create_time|date:"Y-m-d" }}&nbsp;{{ mood.create_time|time:"H:i:s" }}</small></p>
    </div>
    <div class="col-md-12 text-right">
        <hr>
        <a role="button" class="btn btn-warning" href="{% url 'mood-time-line' %}">更多</a>
    </div>
</div>