Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles import views as static_views
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^authentication/', include('authentication.urls')),
    url(r'^navbar/', include('navbar.urls')),
    url(r'^link/', include('link.urls')),
    url(r'^mood/', include('mood.urls')),
    url(r'^', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.STATIC_ROOT},
            name='static'),
        url(r'^media/(?P<path>.*)$', static_views.static.serve, {'document_root': settings.MEDIA_ROOT},
            name='media'),

    ]

DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import url

from views import get_ueditor_controller

urlpatterns = [
    url(r'^controller/$',get_ueditor_controller)
]

article/urls.py
from django.conf.urls import url
from article import views

urlpatterns = [
    url('^category/add/$', views.CategoryCreateView.as_view(), name='category-add'),
    url('^category/list/$', views.CategoryListView.as_view(), name='category-list'),
    url('^category/(?P<pk>[0-9]+)/update/$', views.CategoryUpdateView.as_view(), name='category-update'),
    url('^category/(?P<pk>[0-9]+)/delete/$', views.CategoryDeleteView.as_view(), name='category-delete'),
    url('^category/(?P<pk>[0-9]+)/$', views.CategoryArticleListView.as_view(), name='category-article-list'),

    url('^blog/add/$', views.BlogCreateView.as_view(), name='blog-add'),
    url('^blog/(?P<pk>[0-9]+)/update/$', views.BlogUpdateView.as_view(), name='blog-update'),
    url('^blog/(?P<pk>[0-9]+)/delete/$', views.BlogDeleteView.as_view(), name='blog-delete'),
    url('^blog/(?P<pk>[0-9]+)/detail/$', views.BlogDetailView.as_view(), name='blog-detail'),
    # url('^blog/list/all/$', views.BlogListView.as_view(), name='blog-list'),
    url('^blog/list/personal/$', views.PersonalBlogListView.as_view(), name='blog-list-personal'),

    url('^pure_page/add/$', views.PurePageCreateView.as_view(), name='pure-page-add'),
    url('^pure_page/(?P<pk>[0-9]+)/update/$', views.PurePageUpdateView.as_view(), name='pure-page-update'),
    url('^pure_page/(?P<pk>[0-9]+)/delete/$', views.PurePageDeleteView.as_view(), name='pure-page-delete'),
    # url('^pure_page/(?P<pk>[0-9]+)/detail/$', views.PurePageDetailView.as_view(), name='pure-page-detail'),
    url('^pure_page/list/personal/$', views.PurePageListView.as_view(), name='pure-page-list'),

]

article/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name


class Essay(models.Model):
    title = models.CharField(max_length=128)
    publish_time = models.DateTimeField(auto_now_add=True)
    modification_time = models.DateTimeField(auto_now=True)
    publish_time.editable = True
    modification_time.editable = True
    show_times = models.IntegerField(default=0)

    class Meta:
        abstract = True
        ordering = ['-publish_time']

    def __unicode__(self):
        return self.title


class Blog(Essay):
    category = models.ForeignKey(Category)
    author = models.ForeignKey(User)
    summary = models.TextField()
    content = UEditorField(imagePath="article/blog/images/", filePath="article/blog/files/")


class PurePage(Essay):
    content = UEditorField(imagePath="article/pure_page/images/", filePath="article/pure_page/files/")

    def get_absolute_url(self):
        return reverse('pure-page-detail', args=[str(self.id)])

mood/models.py
from __future__ import unicode_literals

from django.db import models
from Blog.local_settings import storage

MOOD_TYPE_CHOICE = (
    ('T', 'Text'),
    ('I', 'Image'),
    ('B', 'block_quote')
)


class Mood(models.Model):
    title = models.CharField(max_length=128, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    mood_type = models.CharField(max_length=1, choices=MOOD_TYPE_CHOICE, default='T')
    image = models.ImageField(upload_to='./image/mood/%Y/%m/%d/', null=True, blank=True)
    create_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.content

    def get_small_image_url(self):
        if storage == 'qiniu':
            return self.image.url + '?imageView2/2/w/350'
        else:
            return self.image.url

    class Meta:
        ordering = ['-create_time']

article/views.py
from django.core.urlresolvers import reverse_lazy
from article.models import Category, Blog, PurePage
from utils.mixin import AjaxableResponseMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import JsonResponse, Http404
from website.mixin import FrontMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404


class CategoryCreateView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    login_url = reverse_lazy('user-login')
    model = Category
    fields = ['name']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('category-list')

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['active_page'] = 'category-add'
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user-login')
    model = Category
    context_object_name = 'category_list'

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['active_page'] = 'category-list'
        return context


class CategoryArticleListView(FrontMixin, ListView):
    template_name = 'website/frontend/homepage.html'
    model = Blog
    paginate_by = 5
    context_object_name = 'article_list'

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Blog.objects.filter(category=category)


class CategoryUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    login_url = reverse_lazy('user-login')
    model = Category
    context_object_name = 'category'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('category-list')
    fields = ['name']

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        context['active_page'] = 'category-update'
        return context


class CategoryDeleteView(LoginRequiredMixin, AjaxableResponseMixin, DeleteView):
    login_url = reverse_lazy('user-login')
    model = Category
    success_url = reverse_lazy('category-list')

    def post(self, request, *args, **kwargs):
        super(CategoryDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})


class BlogCreateView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    login_url = reverse_lazy('user-login')
    model = Blog
    template_name_suffix = '_create_form'
    fields = ['title', 'content', 'summary', 'category']
    success_url = reverse_lazy('blog-list-personal')

    def get_context_data(self, *args, **kwargs):
        context = super(BlogCreateView, self).get_context_data(**kwargs)
        context['active_page'] = 'blog-add'
        context['category_list'] = Category.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.show_times = 0
        return super(BlogCreateView, self).form_valid(form)


class PersonalBlogListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user-login')
    context_object_name = 'essay_list'
    template_name = 'article/blog_list.html'
    model = Blog

    def get_context_data(self, *args, **kwargs):
        context = super(PersonalBlogListView, self).get_context_data(**kwargs)
        context['active_page'] = 'blog-list'
        return context


class BlogUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    login_url = reverse_lazy('user-login')
    model = Blog
    context_object_name = 'blog'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('blog-list-personal')
    fields = ['title', 'category', 'summary', 'content']

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        blog = Blog.objects.get(pk=kwargs.get('pk'))
        if blog.author != user:
            raise Http404
        else:
            return super(BlogUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(BlogUpdateView, self).get_context_data(**kwargs)
        context['active_page'] = 'blog-update'
        context['category_list'] = Category.objects.all()
        return context


class BlogDeleteView(LoginRequiredMixin, AjaxableResponseMixin, DeleteView):
    login_url = reverse_lazy('user-login')
    model = Blog
    success_url = reverse_lazy('blog-list-personal')

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        blog = Blog.objects.get(pk=kwargs.get('pk'))
        if blog.author != user:
            raise Http404
        else:
            return super(BlogDeleteView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        super(BlogDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})


class BlogDetailView(FrontMixin, DetailView):
    model = Blog
    context_object_name = 'article'
    template_name = 'article/article_detail.html'

    def get_object(self, queryset=None):
        obj = super(BlogDetailView, self).get_object()
        obj.show_times += 1
        obj.save()
        return obj


# class BlogListView(FrontMixin, ListView):
#     model = Blog
#     context_object_name = 'article_list'
#     template_name = 'article/article_list.html'
#     paginate_by = 10


class PurePageCreateView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    login_url = reverse_lazy('user-login')
    model = PurePage
    template_name_suffix = '_create_form'
    fields = ['title', 'content']
    success_url = reverse_lazy('pure-page-list')

    def get_context_data(self, *args, **kwargs):
        context = super(PurePageCreateView, self).get_context_data(**kwargs)
        context['active_page'] = 'pure-page-add'
        return context


class PurePageUpdateView(LoginRequiredMixin, AjaxableResponseMixin, UpdateView):
    login_url = reverse_lazy('user-login')
    model = PurePage
    template_name_suffix = '_update_form'
    context_object_name = 'page'
    fields = ['title', 'content']
    success_url = reverse_lazy('pure-page-list')

    def get_context_data(self, *args, **kwargs):
        context = super(PurePageUpdateView, self).get_context_data(**kwargs)
        context['active_page'] = 'pure-page-update'
        return context


class PurePageDeleteView(LoginRequiredMixin, AjaxableResponseMixin, DeleteView):
    login_url = reverse_lazy('user-login')
    model = PurePage
    success_url = reverse_lazy('pure-page-list')

    def post(self, request, *args, **kwargs):
        super(PurePageDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})


class PurePageListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('user-login')
    model = PurePage
    context_object_name = 'page_list'
    template_name = 'article/purepage_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PurePageListView, self).get_context_data(**kwargs)
        context['active_page'] = 'pure-page-list'
        return context

# class PurePageDetailView(FrontMixin, DetailView):
#     model = PurePage
#     context_object_name = 'article'
#     template_name = 'article/article_detail.html'

templates/article/article_list.html
{% extends 'website/frontend_base.html' %}

{% block title %}文章列表{% endblock %}

{% block external_head %}{% endblock %}


{% block left %}
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">动态列表</h3>
            </div>
            <div class="list-group">
            {% for article in article_list %}
                <a href="{% url 'blog-detail' article.id %}" class="list-group-item">
                    <h4 class="list-group-item-heading">[{{ article.category }}]{{ article.title }}</h4>
                    <p class="list-group-item-text">{{ article.author }}</p>
                    <p class="list-group-item-text text-info">{{ article.modification_time|date:"Y-m-d" }}&nbsp;{{ article.modification_time|time:"H:i" }}</p>
                </a>
            {% endfor %}
            {% include 'utils/pagination.html' %}
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}{% endblock %}

templates/article/article_weight.html
{% load custom_template_tag %}
<div class="col-md-12">
    {% for article in article_list %}
        <div class="col-md-12 col-xs-12 article">
            <div class="col-md-12 col-xs-12">
                <h2><a href="{% url 'blog-detail' article.id %}">{{ article.title }}</a></h2>
                <p><small><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>{{ article.publish_time|date:"Y-m-d" }}&nbsp;{{ article.publish_time|time:"H:i" }}</small></p>

                <blockquote>
                    <p class="text-danger">原创文章，转载请注明出处和作者。</p>
                </blockquote>
            </div>
            <div class="col-md-12 col-xs-12">
                {% markdown2html article.summary as content %}
                {{ content|safe }}
                <hr>
            </div>

            <div class="col-md-6 col-xs-6">
                <a href="{% url 'category-article-list' article.category.id %}"><span class="label label-default"><span class="text-left"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>&emsp;{{ article.category }}</span></span></a>
            </div>
            <div class="col-md-6 text-right col-xs-6">
                <a role="button" class="btn btn-info btn-xs" href="{% url 'blog-detail' article.id %}"><span class="glyphicon glyphicon-console" aria-hidden="true"></span>&emsp;查看详情</a>
            </div>
        </div>
    {% endfor %}
    {% include 'utils/pagination.html' %}

</div>

templates/article/blog_create_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    添加文章
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="category" class="col-sm-1 control-label">分类：</label>
                <div class="col-sm-9">
                    <select name="category" id="category" class="form-control">
                        {% for category in category_list %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="summary" class="col-sm-1 control-label">摘要：</label>
                <div class="col-sm-9">
                    <textarea name="summary" id="summary" rows="5" wrap="hard" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain"></script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=article/blog/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=article/blog/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "blog-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>


{% endblock %}

templates/article/blog_list.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    个人文章列表
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <table class="table table-hover table-responsive table-condensed dashboard-table">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>标题</th>
                    <th>发布时间</th>
                    <th>修改时间</th>
                    <th>阅读次数</th>
                    <th>动作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in essay_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>[{{ item.category }}]{{ item.title }}</td>
                        <td>{{ item.publish_time }}</td>
                        <td>{{ item.modification_time }}</td>
                        <td>{{ item.show_times }}</td>
                        <td>
                            <a href="{% url 'blog-update' item.pk %}" class="btn btn-warning" role="button">修改</a>
                            &emsp;
                            <button class="btn btn-danger" role="button" data-id="{{ item.id }}">删除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('.btn-danger').on('click',
            function (e) {
                e.preventDefault();
                var dom_item = this;
                $.ajax({
                    type:"POST",
                    dataType:'json',
                    data:{},
                    url:'{% url "blog-delete" 00 %}'.replace('0', this.dataset['id']),
                    success:function(data){
                        var state = data.state;
                        if(state == 'success'){
                            dom_item.parentElement.parentElement.setAttribute('hidden','');
                            showModal('success', "删除成功！")
                        }
                    },
                    error:function(data){
                        alert(data);
                    }
                });
            })
    </script>
{% endblock %}

templates/article/blog_nav.html
<ul class="nav nav-sidebar">
    <li id="blog-list"><a href="{% url 'blog-list-personal' %}">文章-列表</a></li>
    <li id="blog-add"><a href="{% url 'blog-add' %}">文章-添加</a></li>
    <li id="blog-update"><a href="{% url 'blog-list-personal' %}">文章-更新</a></li>
</ul>

templates/article/blog_update_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    更新文章
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required value="{{ blog.title }}">
                </div>
            </div>
            <div class="form-group">
                <label for="category" class="col-sm-1 control-label">分类：</label>
                <div class="col-sm-9">
                    <select name="category" id="category" class="form-control">
                        {% for category in category_list %}
                            <option value="{{ category.id }}" {% if blog.category_id == category.id %}
                                selected
                            {% endif %} >{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="summary" class="col-sm-1 control-label">摘要：</label>
                <div class="col-sm-9">
                    <textarea name="summary" id="summary" rows="5" wrap="hard" class="form-control">{{ blog.summary }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain">{{ blog.content|safe }}</script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=article/blog/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=article/blog/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">更新</button>
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "blog-update" blog.pk %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "更新成功");
                        } else {
                            showModal('danger', "更新失败");
                        }
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>


{% endblock %}

templates/article/category_create_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    添加文章分类
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="name" class="col-sm-3 col-sm-offset-2 control-label">名称：</label>
                <div class="col-sm-3">
                    <input type="text" id="name" name="name" class="form-control" required>
                </div>
            </div>
            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "category-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>

{% endblock %}

templates/article/category_nav.html
<ul class="nav nav-sidebar">
    <li id="category-list"><a href="{% url 'category-list' %}">文章类别-列表</a></li>
    <li id="category-add"><a href="{% url 'category-add' %}">文章类别-添加</a></li>
    <li id="category-update"><a href="{% url 'category-list' %}">文章类别-更新</a></li>
</ul>

templates/article/purepage_create_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    添加静态页面
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain"></script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=article/pure_page/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=article/pure_page/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "pure-page-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>


{% endblock %}

templates/article/purepage_nav.html
<ul class="nav nav-sidebar">
    <li id="pure-page-list"><a href="{% url 'pure-page-list' %}">静态页面-列表</a></li>
    <li id="pure-page-add"><a href="{% url 'pure-page-add' %}">静态页面-添加</a></li>
    <li id="pure-page-update"><a href="{% url 'pure-page-list' %}">静态页面-更新</a></li>
</ul>

templates/article/purepage_update_form.html
{% extends 'website/backend/backend_base.html' %}

{% block option-title %}
    修改静态页面
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required value="{{ page.title }}">
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-1 control-label">内容：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain">{{ page.content|safe }}</script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=article/pure_page/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=article/pure_page/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">修改</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "pure-page-update" page.pk %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "修改成功");
                        } else {
                            showModal('danger', "修改失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>


{% endblock %}